create table BOOKS (
	ID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	NAME	 varchar(120),
	AUTHOR	 varchar(30),
	ISBN	 varchar(20),
	YEAR	 varchar(4)
	);
	
	
create table CONTENT_INDEX (
	SEQ int NOT NULL,
	BOOK_ID int NOT NULL references BOOKS(ID),
	CNAME	 varchar(120),
	Page	 int,
	PRIMARY KEY (SEQ,BOOK_ID)
	);
	